'use strict';

import telNumber from "./modules/numtel";
import menu from "./modules/menu";
import price from "./modules/price";
import maskPhone from "./modules/maskPhone";
import modalPrivacy from "./modules/modalPrivacy";
import formulaBlock from "./modules/formulaBlock";
import SliderCarousel from "./modules/sliderCarousel";
import comments from "./modules/comments";
import sliderCarouselTab from "./modules/carouselTab";
import portfolio from "./modules/portfolio";
import typesRepair from "./modules/typesRepair";
import accordion from "./modules/accordion";
import tabs from "./modules/tabs";
import documents from "./modules/documents";
import disengAdd from "./modules/desing";
import desingAdd from "./modules/desing";
import modPortfolio from "./modules/modPortfolio";

telNumber();
menu();
price();
modalPrivacy();
formulaBlock();
comments();
typesRepair();
accordion();
tabs();
documents();
desingAdd();
modPortfolio();